version: '3.7'

services:

  web_app:
    container_name: web_app
    build:
      context: ./MayFlower-WebPortal
      dockerfile: Dockerfile
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    tty: true
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true